#!/usr/bin/env bash
CLASSPATH=(
  "B42MP.jar"
  "log4j-core-2.24.3.jar"
  "log4j-api-2.24.3.jar"
  "commons-math3-3.6.1.jar"
  "asm-9.1.jar"
  "asm-analysis-9.1.jar"
  "asm-tree-9.1.jar"
  "asm-util-9.1.jar"
  "guava-30.1.1-jre.jar"
  "commons-codec-1.10.jar"
  "commons-compress-1.27.1.jar"
  "commons-io-2.18.0.jar"
  "core-3.2.1.jar"
  "guava-23.0.jar"
  "imgui-binding-1.86.11-8-g3e33dde.jar"
  "istack-commons-runtime.jar"
  "jassimp.jar"
  "javacord-3.8.0-shaded.jar"
  "javase-3.2.1.jar"
  "javax.activation-api.jar"
  "jaxb-api.jar"
  "jaxb-runtime.jar"
  "lwjgl-glfw-natives-linux.jar"
  "lwjgl-glfw.jar"
  "lwjgl-jemalloc-natives-linux.jar"
  "lwjgl-jemalloc.jar"
  "lwjgl-natives-linux.jar"
  "lwjgl-opengl-natives-linux.jar"
  "lwjgl-opengl.jar"
  "lwjgl.jar"
  "lwjgl_util.jar"
  "sqlite-jdbc-3.48.0.0.jar"
  "totp-1.0.jar"
  "trove-3.0.3.jar"
  "uncommons-maths-1.2.3.jar"
  "."
)
PZ_CLASSPATH=$(
  IFS=:
  echo "${CLASSPATH[*]}"
)
JAVA_ARGS=(
  # "-verbose:class"
  "-debug"
  "-Djava.awt.headless=true"
  "-Dzomboid.steam=1"
  "-Dzomboid.znetlog=1"
  "-Djava.library.path=linux64/:."
  "-Djava.security.egd=file:/dev/./urandom"
  "-XX:+UseZGC"
  "-XX:-OmitStackTraceInFastThrow"
  "-XX:-CreateCoredumpOnCrash"
)
export LD_LIBRARY_PATH="/home/container/.steam/sdk64/:/home/container/steamcmd/linux64/:${LD_LIBRARY_PATH}"
cd projectzomboid
exec jre64/bin/java "${JAVA_ARGS[@]}" -cp "${PZ_CLASSPATH}" io.pzstorm.storm.core.Launcher2 "$@"